services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /srv/app
        volumes:
            - ./:/srv/app
    nginx:
        image: nginx:1.29
        volumes:
            - ./public:/usr/share/nginx/html
        ports:
            - "8289:80"
